Fix #11: export of connectors supported
STARIONGROUP/ea-modelkit pull request #12
Opened 2024-12-10 10:32 UTC by antoineatstariongroup

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/STARIONGROUP/ea-modelkit/pulls) open
- [x] I have verified that I am following the EA-ModelKit [code style guidelines](https://raw.githubusercontent.com/STARIONGROUP/ea-modelkit/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix #11 

Connectors are also part of the export

2024-12-10 13:53 UTC, lxatstariongroup approved these changes

2024-12-11 10:12 UTC, lxatstariongroup approved these changes

2024-12-13 07:45 UTC, samatstariongroup requested changes
add some docs to shell script

2024-12-13 07:45 UTC, samatstariongroup commented on MSIHelper.sh
> +#!/bin/bash
please add some docs to explain the purpose of this script

2024-12-16 10:25 UTC, samatstariongroup approved these changes

2024-12-16 10:27 UTC, lxatstariongroup approved these changes

2024-12-16 10:28 UTC, merged