Fix #7 : Export to excel for selected TaggedValue
STARIONGROUP/ea-modelkit pull request #8
Opened 2024-12-05 12:14 UTC by antoineatstariongroup

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/STARIONGROUP/ea-modelkit/pulls) open
- [x] I have verified that I am following the EA-ModelKit [code style guidelines](https://raw.githubusercontent.com/STARIONGROUP/ea-modelkit/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix #7 

- Possibility to select if a type/stereotype should exported or not
- When set a exportable, possibility to select which taggedValue will be exported

2024-12-06 09:18 UTC, samatstariongroup requested changes

2024-12-06 09:18 UTC, samatstariongroup commented on EA-ModelKit/Model/Export/ExportableElement.cs
> +                    ? string.Join("\n", existingValue.Select(x => x.Value))
can this be instead of `\n` the `Environment.Newline?

2024-12-06 09:18 UTC, samatstariongroup commented on EA-ModelKit.Tests/Converters/BooleanToVisibilityConverterTestFixture.cs
> +}
Please add newline at the end of each file. We had this rule earlier and it got removed. There is good reason to make diffs more readible when using git and git extensions

2024-12-06 09:38 UTC, antoineatstariongroup commented on EA-ModelKit.Tests/Converters/BooleanToVisibilityConverterTestFixture.cs
> +}
A new line is already present on each file, just the Tests.csproj one that missed it

2024-12-06 09:38 UTC, antoineatstariongroup commented on EA-ModelKit/Model/Export/ExportableElement.cs
> +                    ? string.Join("\n", existingValue.Select(x => x.Value))
Changed and tested

2024-12-06 09:39 UTC, lxatstariongroup approved these changes
Very nice code again, Antoine!

2024-12-06 09:39 UTC, lxatstariongroup commented on EA-ModelKit/App.cs
> +            var folderPath = Path.GetDirectoryName(typeof(App).Assembly.Location);
For performance, this result could be stored in a private static field. Not a reason to stop landing.

2024-12-09 08:33 UTC, samatstariongroup approved these changes

2024-12-09 08:34 UTC, merged